CONFIGS = {

    # AGENT CONFIGS
    'NUM_AGENT_NODES' : 4,
    'PRED_HORIZON' : 5,
    'HIDDEN_DIM' : 1024,
    'NUM_ATT_HEADS' : 4, # REPLACE NODE EBD DIM 
    'HEAD_DIM' : 16, # REPLACE NODE EMB DIM 
    'AGENT_STATE_EMB_DIM' : 16,
    'EDGE_POS_DIM': 2,


    # DEMO CONFIGS (BOTH)
    'NUM_SAMPLED_POINTCLOUDS' : 3,
    # PSEUDO-DEMO CONFIGS
    "DEMO_MAX_LENGTH" : 6,
    'DEMO_MIN_LENGTH' : 2,
    # DEMO GIVEN CONFIGS
    "DEMO_LENGTH" : 6,



    # TRAINING CONFIGS:
    'NUM_DIFFUSION_STEPS' : 500,
    'NUM_DEMO_GIVEN' : 3,
    'NUM_STEPS_PER_EPOCH' : 200,
    'NUM_EPOCHS' : 20,
    'SAVE_MODEL' : True,
    'MODEL_FILE_PATH' :  "instant_policy.pth",
    'TRAINING_MAX_TRANSLATION' : 500, # WIDTH^2 + HEIGHT^2 SQRT
    'BATCH_SIZE' : 20,

    # TESTING CONFIGS
    'MAX_INFERENCE_ITER' : 50,
    'TESTING_MAX_TRANSLATION' : 1000, # WIDTH^2 + HEIGHT^2 SQRT

}