CONFIGS = {

    # AGENT CONFIGS
    'NUM_AGENT_NODES' : 4,
    'PRED_HORIZON' : 5,
    'HIDDEN_DIM' : 256,
    'NODE_EMB_DIM' : 64,
    'EDGE_EMB_DIM' : 64,
    'AGENT_STATE_EMB_DIM' : 16,
    'EDGE_POS_DIM': 2,


    # DEMO CONFIGS (BOTH)
    'NUM_SAMPLED_POINTCLOUDS' : 30,
    # PSEUDO-DEMO CONFIGS
    "DEMO_MAX_LENGTH" : 6,
    'DEMO_MIN_LENGTH' : 2,
    # DEMO GIVEN CONFIGS
    "DEMO_LENGTH" : 6,



    # TRAINING CONFIGS:
    'NUM_DIFFUSION_STEPS' : 500,
    'NUM_DEMO_GIVEN' : 3,
    'NUM_STEPS_PER_EPOCH' : 1000,
    'NUM_EPOCHS' : 100,
    'SAVE_MODEL' : True,
    'MODEL_FILE_PATH' :  "instant_policy.pth",
    'TRAINING_MAX_TRANSLATION' : 500, # WIDTH^2 + HEIGHT^2 SQRT
    'BATCH_SIZE' : 10,

    # TESTING CONFIGS
    'MAX_INFERENCE_ITER' : 50,
    'TESTING_MAX_TRANSLATION' : 1000, # WIDTH^2 + HEIGHT^2 SQRT

}